#!/bin/sh
#
# Builds UnRAR from source as a static library and wraps it into an
# xcframework consumed by the QooUnrarBridge target's Objective-C++ wrapper
# [LC-11][B-03]. UnRAR source is freeware but NOT MIT/BSD — see
# THIRD-PARTY-NOTICES.md and ThirdParty/unrar/license.txt. In particular it
# must not be used to develop a RAR (WinRAR) compatible archiver [LC-26].
#
# This script is skipped entirely for PERMISSIVE_ONLY_BUILD, which uses
# libarchive's RAR reader instead [LC-12][LC-13].
#
# Usage:
#   Scripts/build-unrar.sh
#
# Output (all git-ignored, regenerated by this script):
#   ThirdParty/unrar/libunrar.xcframework/   binary consumed by Package.swift
#   Sources/QooUnrarBridge/raros.hpp         vendored UnRAR headers (committed,
#   Sources/QooUnrarBridge/dll.hpp           unmodified, used only by the .mm
#                                             bridge — never exposed to Swift)

set -eu

UNRAR_VERSION="7.2.7"
UNRAR_SHA256="01d903a7dcf413cb2925696d7796e48e38d471f79bfe7ef3ad2aebf6c12dbefd"
UNRAR_URL="https://www.rarlab.com/rar/unrarsrc-${UNRAR_VERSION}.tar.gz"
MIN_MACOS="13.0"
ARCHS="arm64 x86_64"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TP_DIR="${ROOT_DIR}/ThirdParty/unrar"
BUILD_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/qoo-unrar-build.XXXXXX")"
trap 'rm -rf "${BUILD_ROOT}"' EXIT
SRC_DIR="${BUILD_ROOT}/src"
TARBALL="${SRC_DIR}/unrarsrc-${UNRAR_VERSION}.tar.gz"
EXTRACTED_DIR="${SRC_DIR}/unrar"
XCFRAMEWORK="${TP_DIR}/libunrar.xcframework"
BRIDGE_DIR="${ROOT_DIR}/Sources/QooUnrarBridge"
SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"

# Headers needed to compile QooUnrarBridge.mm against the public
# "RARDLL" C API (dll.hpp). raros.hpp is required first: it defines _UNIX
# for __APPLE__, which dll.hpp needs to map HANDLE/LPARAM/... to plain C
# types. Neither header is exposed to Swift (see Sources/QooUnrarBridge/
# include/QooUnrarBridge.h for the actual public surface).
BRIDGE_HEADERS="raros.hpp dll.hpp"

echo "==> UnRAR ${UNRAR_VERSION} build starting"
mkdir -p "${SRC_DIR}"

# ---- 1. Download + verify -------------------------------------------------
if [ ! -f "${TARBALL}" ]; then
    echo "==> downloading ${UNRAR_URL}"
    curl -sL -o "${TARBALL}" "${UNRAR_URL}"
fi

ACTUAL_SHA256="$(shasum -a 256 "${TARBALL}" | awk '{print $1}')"
if [ "${ACTUAL_SHA256}" != "${UNRAR_SHA256}" ]; then
    echo "!! checksum mismatch for ${TARBALL}"
    echo "   expected ${UNRAR_SHA256}"
    echo "   actual   ${ACTUAL_SHA256}"
    exit 1
fi
echo "==> checksum OK"

# ---- 2. Extract -------------------------------------------------------------
# The tarball's own top-level entry is "unrar/", matching $EXTRACTED_DIR.
if [ ! -d "${EXTRACTED_DIR}" ]; then
    echo "==> extracting"
    tar xzf "${TARBALL}" -C "${SRC_DIR}"
fi

# ---- 3. Build the RARDLL object set per architecture -----------------------
# We only need `make lib`'s object list (unrar's own makefile also links a
# .so with `-shared`, which we don't need but is harmless to let complete).
LIBS_TO_LIPO=""
for ARCH in ${ARCHS}; do
    BUILD_DIR="${BUILD_ROOT}/build-${ARCH}"
    echo "==> building for ${ARCH}"
    rm -rf "${BUILD_DIR}"
    cp -R "${EXTRACTED_DIR}" "${BUILD_DIR}"
    (
        cd "${BUILD_DIR}"
        make -j"$(sysctl -n hw.ncpu)" lib \
            CXX="clang++ -arch ${ARCH} -isysroot ${SDK_PATH} -mmacosx-version-min=${MIN_MACOS}" \
            > build.log 2>&1
    )
    LIBS_TO_LIPO="${LIBS_TO_LIPO} ${BUILD_DIR}/libunrar.a"
done

# ---- 4. Combine into a universal static library ----------------------------
UNIVERSAL_LIB="${BUILD_ROOT}/libunrar-universal.a"
echo "==> creating universal static library"
# shellcheck disable=SC2086
lipo -create ${LIBS_TO_LIPO} -output "${UNIVERSAL_LIB}"
lipo -info "${UNIVERSAL_LIB}"

# ---- 5. Wrap into an xcframework -------------------------------------------
echo "==> creating xcframework"
mkdir -p "${TP_DIR}"
rm -rf "${XCFRAMEWORK}"
xcodebuild -create-xcframework \
    -library "${UNIVERSAL_LIB}" \
    -output "${XCFRAMEWORK}" \
    > "${TP_DIR}/xcframework.log" 2>&1

# ---- 6. Vendor the bridge-internal headers ---------------------------------
echo "==> copying UnRAR headers used by QooUnrarBridge.mm"
mkdir -p "${BRIDGE_DIR}"
for H in ${BRIDGE_HEADERS}; do
    cp "${EXTRACTED_DIR}/${H}" "${BRIDGE_DIR}/${H}"
done

echo "==> done. libunrar.xcframework: ${XCFRAMEWORK}"
