#!/bin/sh
#
# Builds libarchive from source as a static library and wraps it into an
# xcframework consumed by the CLibarchive SwiftPM target. [LC-15][B-02]
#
# qooLibrary does not link against the system libarchive.dylib; a fixed
# version is vendored and built here instead, so behavior is reproducible
# across machines and macOS versions.
#
# Usage:
#   Scripts/build-libarchive.sh
#
# Output (git-ignored, regenerated by this script):
#   ThirdParty/libarchive/libarchive.xcframework/  binary consumed by Package.swift
#   Sources/CLibarchive/include/*.h                vendored public headers (committed)
#
# NOTE: autoconf's `configure` refuses to run from a source directory whose
# path contains spaces ("unsafe srcdir value"). To stay robust regardless of
# where this repository is checked out, all downloading/extracting/building
# happens in a temp directory outside the repo; only the final xcframework
# and headers are copied back in.

set -eu

LIBARCHIVE_VERSION="3.8.9"
LIBARCHIVE_SHA256="f5a6539059cf5e597dbeda37bfa4874b1e8dea063c8d93bf85a2b44af90a5bd4"
LIBARCHIVE_URL="https://github.com/libarchive/libarchive/releases/download/v${LIBARCHIVE_VERSION}/libarchive-${LIBARCHIVE_VERSION}.tar.gz"
MIN_MACOS="13.0"
ARCHS="arm64 x86_64"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TP_DIR="${ROOT_DIR}/ThirdParty/libarchive"
BUILD_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/qoo-libarchive-build.XXXXXX")"
trap 'rm -rf "${BUILD_ROOT}"' EXIT
SRC_DIR="${BUILD_ROOT}/src"
TARBALL="${SRC_DIR}/libarchive-${LIBARCHIVE_VERSION}.tar.gz"
EXTRACTED_DIR="${SRC_DIR}/libarchive-${LIBARCHIVE_VERSION}"
XCFRAMEWORK="${TP_DIR}/libarchive.xcframework"
HEADERS_OUT="${ROOT_DIR}/Sources/CLibarchive/include"
SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"

# libarchive's public API surface. Internal headers (archive_platform.h,
# archive_string.h, ...) are intentionally not vendored.
PUBLIC_HEADERS="archive.h archive_entry.h"

echo "==> libarchive ${LIBARCHIVE_VERSION} build starting"
mkdir -p "${SRC_DIR}"

# ---- 1. Download + verify -------------------------------------------------
if [ ! -f "${TARBALL}" ]; then
    echo "==> downloading ${LIBARCHIVE_URL}"
    # --fail matters: without it an HTTP error body is written into ${TARBALL}
    # and the run fails as a *checksum mismatch*, which looks like tampering and
    # invites updating the pinned hash. Keep the two failure modes distinct
    # (see build-unrar.sh for the CI incident that prompted this).
    if ! curl -fsSL --retry 3 --retry-delay 2 --retry-all-errors \
             -o "${TARBALL}" "${LIBARCHIVE_URL}"; then
        echo "!! download failed for ${LIBARCHIVE_URL}"
        echo "   The transfer did not succeed — do not touch LIBARCHIVE_SHA256."
        rm -f "${TARBALL}"
        exit 1
    fi
fi

ACTUAL_SHA256="$(shasum -a 256 "${TARBALL}" | awk '{print $1}')"
if [ "${ACTUAL_SHA256}" != "${LIBARCHIVE_SHA256}" ]; then
    echo "!! checksum mismatch for ${TARBALL}"
    echo "   expected ${LIBARCHIVE_SHA256}"
    echo "   actual   ${ACTUAL_SHA256}"
    echo "   size     $(wc -c < "${TARBALL}") bytes"
    echo "   The download reported success, so this is a genuine content change."
    echo "   Verify the source independently before changing LIBARCHIVE_SHA256."
    exit 1
fi
echo "==> checksum OK"

# ---- 2. Extract -------------------------------------------------------------
if [ ! -d "${EXTRACTED_DIR}" ]; then
    echo "==> extracting"
    tar xzf "${TARBALL}" -C "${SRC_DIR}"
fi

# ---- 3. Configure + build per architecture ---------------------------------
LIBS_TO_LIPO=""
for ARCH in ${ARCHS}; do
    BUILD_DIR="${BUILD_ROOT}/build-${ARCH}"
    echo "==> configuring for ${ARCH}"
    mkdir -p "${BUILD_DIR}"
    (
        cd "${BUILD_DIR}"
        CC="clang -arch ${ARCH} -isysroot ${SDK_PATH} -mmacosx-version-min=${MIN_MACOS}" \
        "${EXTRACTED_DIR}/configure" \
            --host="${ARCH}-apple-darwin" \
            --disable-shared --enable-static \
            --without-nettle --without-openssl --without-xml2 --without-expat \
            --without-lz4 --without-lzo2 --without-zstd --without-lzma \
            --disable-bsdtar --disable-bsdcpio --disable-bsdcat \
            > configure.log 2>&1
    )
    echo "==> building for ${ARCH}"
    (
        cd "${BUILD_DIR}"
        make -j"$(sysctl -n hw.ncpu)" libarchive.la > make.log 2>&1
    )
    LIBS_TO_LIPO="${LIBS_TO_LIPO} ${BUILD_DIR}/.libs/libarchive.a"
done

# ---- 4. Combine into a universal static library ----------------------------
UNIVERSAL_LIB="${BUILD_ROOT}/libarchive-universal.a"
echo "==> creating universal static library"
# shellcheck disable=SC2086
lipo -create ${LIBS_TO_LIPO} -output "${UNIVERSAL_LIB}"
lipo -info "${UNIVERSAL_LIB}"

# ---- 5. Wrap into an xcframework -------------------------------------------
echo "==> creating xcframework"
rm -rf "${XCFRAMEWORK}"
xcodebuild -create-xcframework \
    -library "${UNIVERSAL_LIB}" \
    -output "${XCFRAMEWORK}" \
    > "${TP_DIR}/xcframework.log" 2>&1

# ---- 6. Vendor the public headers into the CLibarchive target -------------
echo "==> copying public headers to Sources/CLibarchive/include"
mkdir -p "${HEADERS_OUT}"
for H in ${PUBLIC_HEADERS}; do
    cp "${EXTRACTED_DIR}/libarchive/${H}" "${HEADERS_OUT}/${H}"
done

echo "==> done. libarchive.xcframework: ${XCFRAMEWORK}"
